let a=1_00;
let b=2_00.5;
let c=1e2;
let d=2.4;
console.log(parseInt(Math.min(a,b,c,d)));
console.log( a*50*Math.floor(d));
console.log(Math.round(d));
console.log(Math.trunc(d));
console.log(Math.floor(d));
console.log(parseInt(d));
// console.log(((b)+(d)).toString);
console.log(Math.floor(b)-(44)*(Math.ceil(d))-(1));